# Generated by Django 5.0.2 on 2024-02-22 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'platos',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('plato', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, to='gestion.plato')),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('plato', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, to='gestion.plato')),
            ],
            options={
                'db_table': 'preparaciones',
                'ordering': ['-orden'],
                'unique_together': {('orden', 'plato')},
            },
        ),
    ]
