# Generated by Django 5.0.2 on 2024-02-24 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_agregue_tabla_cheff'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='cheffId',
            field=models.ForeignKey(db_column='cheff_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
