"""agregue columna activo

Revision ID: 1b1be17c50f9
Revises: 4687975c6767
Create Date: 2024-01-26 20:47:03.886060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1be17c50f9'
down_revision = '4687975c6767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(),
                            server_default='1', nullable=True))
        batch_op.alter_column('sexo', server_default='NINGUNO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
