"""creacion de tablas

Revision ID: bf8fe4fa456e
Revises: 
Create Date: 2024-02-02 20:57:42.110842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8fe4fa456e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tragos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.Enum('ATENTIDO', 'EN_ESPERA', 'PREPARANDO', 'PREPARADO', name='estadopedidosenum'), nullable=True),
    sa.Column('invitado_id', sa.Integer(), nullable=False),
    sa.Column('barman_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barman_id'], ['barmans.id'], ),
    sa.ForeignKeyConstraint(['invitado_id'], ['invitados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('trago_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['trago_id'], ['tragos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_pedidos')
    op.drop_table('pedidos')
    op.drop_table('tragos')
    # ### end Alembic commands ###
