"""removi not null tabla pedido

Revision ID: bfc516a8d30e
Revises: bf8fe4fa456e
Create Date: 2024-02-07 20:04:42.992694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc516a8d30e'
down_revision = 'bf8fe4fa456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('barman_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('barman_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
